export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    ME: "/auth/me",
    REFRESH: "/auth/refresh",
    CHANGE_PASSWORD: "/auth/change-password",
    CHANGE_USERNAME: "/auth/change-username",
  },
  BRANCHES: {
    GET_ALL: "/branches",
    GET_HEADS: "/branches/heads",
    GET_BY_ID: (id) => `/branches/${id}`,
    CREATE: "/branches",
    UPDATE: (id) => `/branches/${id}`,
    DELETE: (id) => `/branches/${id}`,
    TOGGLE_ACTIVE: (id) => `/branches/${id}/toggle-active`,
    TOGGLE_HEAD: (id) => `/branches/${id}/toggle-head`,
    RESET_ADMIN_PASSWORD: (id) => `/branches/${id}/reset-admin-password`,
  },
  DIVISIONS: {
    GET_ALL: "/divisions",
    GET_BY_ID: (id) => `/divisions/${id}`,
    CREATE: "/divisions",
    UPDATE: (id) => `/divisions/${id}`,
    TOGGLE_ACTIVE: (id) => `/divisions/${id}/toggle-active`,
    DELETE: (id) => `/divisions/${id}`,
    CREATE_SUB: (divisionId) => `/divisions/${divisionId}/sub-divisions`,
    UPDATE_SUB: (subId) => `/divisions/sub-divisions/${subId}`,
    TOGGLE_SUB_ACTIVE: (subId) =>
      `/divisions/sub-divisions/${subId}/toggle-active`,
    DELETE_SUB: (subId) => `/divisions/sub-divisions/${subId}`,
  },
  MODULES: {
    GET_ALL: "/modules",
    GET_BY_ID: (id) => `/modules/${id}`,
    CREATE: "/modules",
    UPDATE: (id) => `/modules/${id}`,
    TOGGLE_ACTIVE: (id) => `/modules/${id}/toggle-active`,
    DELETE: (id) => `/modules/${id}`,
  },
  TEACHERS: {
    GET_ALL: "/teachers",
    GET_BY_ID: (id) => `/teachers/${id}`,
    CREATE: "/teachers",
    UPDATE: (id) => `/teachers/${id}`,
    RESET_PASSWORD: (id) => `/teachers/${id}/reset-password`,
    TOGGLE_ACTIVE: (id) => `/teachers/${id}/toggle-active`,
    MIGRATE: (id) => `/teachers/${id}/migrate`,

    PROFILE: {
      GET_ME: "/teachers/profile/me",
      UPDATE_ME: "/teachers/profile/me",
      GET_BRANCHES: "/teachers/profile/branches",
      GET_DIVISIONS: "/teachers/profile/divisions",
      GET_MODULES: "/teachers/profile/modules",
    },
  },
  CERTIFICATES: {
    GET_BRANCHES: "/certificates/branches",
    BULK_CREATE: "/certificates/bulk-create",
    GET_ALL: "/certificates",
    GET_STOCK: "/certificates/stock",
    GET_STOCK_ALERTS: "/certificates/stock-alerts",
    MIGRATE: "/certificates/migrate",
    GET_STATISTICS: "/certificates/statistics",
    GET_MIGRATIONS: "/certificates/migrations",
    GET_LOGS: "/certificates/logs",
    EXPORT_LOGS: "/certificates/logs/export",
  },
  CERTIFICATES_TEACHER: {
    GET_AVAILABLE: "/certificates/available",
    RESERVE: "/certificates/reserve",
    PRINT: "/certificates/print",
    RELEASE: (id) => `/certificates/${id}/release`,
    GET_MY_RESERVATIONS: "/certificates/my-reservations",
    GET_MY_PRINTS: "/certificates/my-prints",
  },
  CERTIFICATE_PDF: {
    UPLOAD: (printId) => `/certificates/prints/${printId}/pdf`,
    DOWNLOAD: (printId) => `/certificates/prints/${printId}/pdf`,
    DELETE: (printId) => `/certificates/prints/${printId}/pdf`,
    LIST: "/certificates/prints/pdfs",
  },
  STUDENTS: {
    SEARCH: "/students/search",
    GET_ALL: "/students",
    GET_BY_ID: (id) => `/students/${id}`,
    GET_HISTORY: (id) => `/students/${id}/history`,
    GET_STATISTICS: "/students/statistics",
    UPDATE: (id) => `/students/${id}`,
    TOGGLE_ACTIVE: (id) => `/students/${id}/toggle-active`,
    MIGRATE: (id) => `/students/${id}/migrate`,
  },
  BACKUP: {
    CREATE: "/backup/create",
    LIST: "/backup/list",
    RESTORE: "/backup/restore",
    DELETE: (id) => `/backup/${id}`,
    DOWNLOAD: (id) => `/backup/download/${id}`,
  },
  HEALTH: "/health",
};
